# To include: Audiobookshelf, File_Browser, Kavita, Plex, Tautulli
# Future expansion: Heimdall, Bazarr, Smokeping, Kometa

version: "3"

services:
  plex: 
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/hd1/Plex/DockerConfigs/plex:/config
      - "/mnt/hd1/Plex/TV Shows:/tv"
      - /mnt/hd1/Plex/Movies:/movies
      - /mnt/hd1/Plex/Web:/web
      - /mnt/hd1/Plex/Prerolls:/Prerolls
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/hd1/Plex/DockerConfigs/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/hd1/Plex/DockerConfigs/kavita:/config
      - /mnt/hd1/Plex/Books:/data
    ports:
      - 5000:5000
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /mnt/hd1/Plex/Audiobooks:/audiobooks
      - /mnt/hd1/Plex/DockerConfigs/audiobookshelf_config:/config
      - /mnt/hd1/Plex/DockerConfigs/audiobookshelf_metadata:/metadata
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  filebrowser:
    image: hurlenko/filebrowser
    user: "${PUID}:${PGID}"
    ports:
      - 443:8080
    volumes:
      - /mnt/hd1:/data
      - /mnt/hd1/Plex/DockerConfigs/filebrowser:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped


